import { AIAnalysisResult } from '../types/ai-types';

/**
 * AI 응답 파싱 및 폴백 처리
 */
export class AIResponseParser {
  /**
   * AI 응답을 파싱하여 AIAnalysisResult로 변환
   */
  static parseAIResponse(response: string, _originalCommand: string): AIAnalysisResult {
    try {
      console.log('🔍 [ai-response-parser] Raw AI response:', response);

      const firstBrace = response.indexOf('{');
      const lastBrace = response.lastIndexOf('}');

      if (firstBrace === -1 || lastBrace === -1 || lastBrace < firstBrace) {
        console.warn('⚠️ [ai-response-parser] No valid JSON object found in response.');
        return { plan: [], reasoning: 'Fallback: No JSON object found in AI response.', rawResponse: response };
      }

      let jsonString = response.substring(firstBrace, lastBrace + 1);
      // 기본적인 JSON 정리
      jsonString = jsonString.replace(/\n/g, '\n').replace(/'/g, "'").replace(/"/g, '"').replace(/&/g, "&").replace(/\r/g, "\r\t").replace(/\t/g, "\t").replace(/\b/g, "\b").replace(/\f/g, "\f");
      jsonString = jsonString.replace(/[\u0000-\u0019]+/g,"");

      console.log('🔧 [ai-response-parser] Sanitized JSON string:', jsonString);
      
      const parsedResponse = JSON.parse(jsonString);

      if (parsedResponse.plan && Array.isArray(parsedResponse.plan)) {
        return {
          plan: parsedResponse.plan,
          reasoning: parsedResponse.reasoning || 'Plan generated by AI.',
          rawResponse: response,
        };
      } else {
        console.warn('⚠️ [ai-parser] Parsed JSON does not contain a valid "plan" array.');
        return { plan: [], reasoning: 'Fallback: Parsed JSON has no valid plan.', rawResponse: response };
      }
    } catch (error: any) {
      console.error('❌ [ai-parser] Failed to parse AI response JSON:', error);
      console.error('❌ [ai-parser] Original response was:', response);

      return { plan: [], reasoning: `Fallback: JSON parsing failed: ${error.message}`, rawResponse: response };
    }
  }
}